services:
  - type: web
    name: gtranslator-api
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: REDIS_ENABLED
        value: "false"
      - key: DEBUG
        value: "false"
      - key: RATE_LIMIT_PER_MINUTE
        value: "100"
      - key: LOG_LEVEL
        value: "INFO"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"