services:
  - type: web
    name: gtranslator-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: REDIS_ENABLED
        value: false
      - key: DEBUG
        value: false
      - key: RATE_LIMIT_PER_MINUTE
        value: 100
      - key: LOG_LEVEL
        value: INFO